### PR TITLE
Update installer path

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by Radon8472** [comment]
Yesterday I found out what the problem was with the install from package repo.

I see that testing of composer.json is not perfekt, but I made this, because testing of "is_dir" returned always true even with the old version.

This is because the installer first creates the dir, that the composer2 error coms (in the 1.0.0 installer) and than the dir gets removed.

A few minutes ago I played with an idea how to fix this.

How about: useing `$this->getVendorAndName()` and check if a file with the package name is in the directory e.g. `MyPwClass.module` (needs check for all possible module-extension `.module`, `.php`, `.module.php`) instead of checking for composer.json?

But maybe I can add this for v1.1.1

**Comment by harikt** [comment]
Sure, you can send it for 1.1.1.

I am gng to do a release 1.1.0 now. I cannot predict my availability even though I love to do ;-) . Family, kids ... ;-) .

**Comment by harikt** [comment]
Do you have an example of the conflicting repo we can test ? So we probably want to go that route ?

**Comment by Radon8472** [comment]
> Do you have an example of the conflicting repo we can test ? So we probably want to go that route ?

I got this false "not-created" error as I tested the example in your comment https://github.com/harikt/pwmoduleinstaller/pull/3#issuecomment-1103617905

**Comment by harikt** [comment]
aah... I did fixed this in 1.1.0. Are you sure you are using the latest version ?

**Comment by Radon8472** [comment]
> aah... I did fixed this in 1.1.0. Are you sure you are using the latest version ?

My last test was with 0edbf18.
In this PR you change the check the caused the problem to `is_dir()` so this false `not-created` error should be fixed.

But as I explained in https://github.com/harikt/pwmoduleinstaller/pull/4#issuecomment-1106044331 this would disable the check if the installer successfull installed the module.
I will try to fix this for v1.1.1

**Pull request merged**
